### ISSUE TITLE
Can't build on Centos 6.7

### ISSUE THREAD

**Issue by ethaniel** [tsgates/mbox#33]
```
/bin/mkdir -p ./linux
cat ./linux/ioctlent.h.in ./linux/x86_64/ioctlent.h.in | \
                gcc -DHAVE_CONFIG_H -I.  -I./linux/x86_64 -I./linux -I./linux -lcrypto  -Wall -Wwrite-strings -g -O2 -E -P - | \
                LC_ALL=C sort -u -k3,3 -k2,2 > linux/ioctlent.h
make  all-am
make[1]: Entering directory `/tmp/passport/se-smart-passport-linux-x64-trial/sample/mbox-master/src'
gcc -DHAVE_CONFIG_H -I.  -I./linux/x86_64 -I./linux -I./linux -lcrypto  -Wall -Wwrite-strings -g -O2 -MT mbox.o -MD -MP -MF .deps/mbox.Tpo -c -o mbox.o mbox.c
In file included from mbox.c:49:
bpf.h:17:27: error: linux/seccomp.h: No such file or directory
In file included from mbox.c:50:
bpf-syscall.h:4: error: invalid use of undefined type 'struct seccomp_data'
bpf-syscall.h:5: error: 'SECCOMP_RET_TRACE' undeclared here (not in a function)
bpf-syscall.h:66: error: 'SECCOMP_RET_ALLOW' undeclared here (not in a function)
mbox.c: In function 'install_seccomp':
mbox.c:291: error: 'SECCOMP_MODE_FILTER' undeclared (first use in this function)
mbox.c:291: error: (Each undeclared identifier is reported only once
mbox.c:291: error: for each function it appears in.)
make[1]: *** [mbox.o] Error 1
make[1]: Leaving directory `/tmp/passport/se-smart-passport-linux-x64-trial/sample/mbox-master/src'
make: *** [all] Error 2

```
